server:
  port: 8080

spring:
  # druid
  datasource:
    url: jdbc:mysql://101.132.138.185:3306/hitravel?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: net.sf.log4jdbc.DriverSpy # com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis
  redis:
#    host: 101.132.138.185
    host: 127.0.0.1
    port: 6379
    #    password: xxxx
    timeout: 3
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
        min-idle: 1

# mybatis
#mybatis:
#  type-aliases-package: com.lixiang.hitravel.domain
#  configuration:
#    map-underscore-to-camel-case: true # 下划线转驼峰
#    default-fetch-size: 100
#    default-statement-timeout: 30
#  mapper-locations: classpath:com/zhang/miaosha/dao/*.xml



